Homework 4
JeRusakow/epam_python_course pull request #4
Opened 2021-04-28 12:47 UTC by JeRusakow

2021-04-30 11:46 UTC, iamthen0ise requested changes
что-то не то с задачей на вывод в потоки, в остальном только поправить по комментариям

2021-04-30 11:46 UTC, iamthen0ise commented on homework4/task1/task_1_read_file.py
> +    datafile.close()
но ведь можно `with open...` и не придется закрывать файл самому.

2021-04-30 11:46 UTC, iamthen0ise commented on homework4/task1/task_1_read_file.py
> +        num = float(line)
кажется без целей дебага эта переменная используется 1 раз. конструкция Try позволяет не делать одноразовые переменные, а прям нагло проверять все на месте)

2021-04-30 11:46 UTC, iamthen0ise commented on homework4/task2/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
но вель Unreachable URL это слишком абстрактно для разных ошибок. Думаю, ты можешь разнообразить экзепшены. Пусть будет показана причина падения, важно понимать — когда нет интернета, а когда 400/500 ошибки.

2021-04-30 11:46 UTC, iamthen0ise commented on homework4/task4/README.md
> +<h2>Running doctests for the module with pytest</h2>
Ридми — всегда круто! 👍

2021-04-30 11:46 UTC, iamthen0ise commented on homework4/task5/task_5_optional.py
> +    fizzes = cycle(["", "", "Fizz"])
мощно, а без cycle получится?) это на интерес вопрос) если нет — так нет

2021-04-30 11:46 UTC, iamthen0ise commented on tests/test_homework4/test_get_print_output.py
> +def test_stderr_write(fake_stderr):
что-то тут не так. в тестах я поменял весь инпут на `abc` и оба теста прошли.
думаю стоит добавить тест с абсолютно рандомным текстом, можно даже автогенерируемым типа  `"".join([chr(random.randint(50,120)) for i in range(10)])`

2021-05-01 23:46 UTC, JeRusakow commented on homework4/task1/task_1_read_file.py
> +    datafile.close()
Переписал с использованием менеджера контекста

2021-05-01 23:48 UTC, JeRusakow commented on homework4/task1/task_1_read_file.py
> +        num = float(line)
Удалил остатки отладочного вывода. Теперь код выглядит лаконичней :)

2021-05-01 23:51 UTC, JeRusakow commented on homework4/task2/task_2_mock_input.py
> +        raise ValueError(f"Unreachable {url}")
Изменил сообщение при втором исключении на "Bad response code: XXX". Пусть их будет два типа

(Пока из интереса смотрел список возможных кодов ответа, наткнулся на забавный номер 418)))

2021-05-01 23:53 UTC, JeRusakow commented on homework4/task5/task_5_optional.py
> +    fizzes = cycle(["", "", "Fizz"])
Получилось)
Ажно сам удивился, насколько просто открывался ларчик

2021-05-01 23:57 UTC, JeRusakow commented on tests/test_homework4/test_get_print_output.py
> +def test_stderr_write(fake_stderr):
Добавил тест с автогенерируемым сообщением.
Оказалось, тесты проходили, потому что assert тестировал совсем не то: проверялось само создание атрибутов у заглушки вместо истории вызовов. 
Было 'assert mock.called_with()' вместо 'mock.assert_called_with()'

2021-05-02 00:10 UTC, JeRusakow commented on homework4/task4/README.md
> +<h2>Running doctests for the module with pytest</h2>
Прочитал мануал по местному диалекту разметки и переписал)

2021-05-04 09:11 UTC, iamthen0ise approved these changes

2021-05-08 20:53 UTC, merged